export const cardsData = [
  {
      id: 1,
      title: "Геологоразведка",
      description: "«Global Energy Solution» предоставляет комплексные услуги по геологоразведке, включая сейсмические исследования и оценку месторождений полезных ископаемых.",
      imgSrc: "/geo.png",
      price: "1 000 000",
      url: "https://ltdfoto.ru/images/2025/03/21/geo.png",
    },
    {
      id: 2,
      title: "Бурение скважин",
      description: "«Global Energy Solution» является лидером в области бурения скважин для извлечения нефти и газа, используя передовые технологии и оборудование.",
      imgSrc: "/oilgas.png",
      price: "2 500 000",
      to: "/catalog/2",
      url: "https://ltdfoto.ru/image/slNVIu",
    },
    {
      id: 3,
      title: "Каротажные исследования",
      description: "«Global Energy Solution» проводит каротажные исследования для оптимизации добычи и повышения эффективности разработки месторождений.",
      imgSrc: "/kar.png",
      price: "1 800 000",
      to: "/catalog/3",
      url: "https://ltdfoto.ru/image/slNCfH",
    },
    {
      id: 4,
      title: "Буровые растворы",
      description: "«Global Energy Solution» предлагает высококачественные буровые растворы для стабилизации скважин и обеспечения безопасного бурения.",
      imgSrc: "/bur.png",
      price: "2 500 000",
      to: "/catalog/4",
      url: "https://ltdfoto.ru/image/slNFqJ",
    },
    {
      id: 5,
      title: "Ингибиторы коррозии",
      description: "«Global Energy Solution» разрабатывает и поставляет ингибиторы коррозии для защиты оборудования и увеличения срока его службы.",
      imgSrc: "/water.png",
      price: "300 000",
      to: "/catalog/5",
      url: "https://ltdfoto.ru/image/slNqmL",
    },
    {
      id: 6,
      title: "Пеногасители",
      description: "«Global Energy Solution» производит эффективные пеногасители, которые уменьшают пенообразование в технологических процессах.",
      imgSrc: "/peno.png",
      price: "200 000",
      to: "/catalog/6",
      url: "https://ltdfoto.ru/image/slWArk",
    },
    {
      id: 7,
      title: "Хранилище",
      description: "«Global Energy Solution» предоставляет услуги по хранению нефти и газа, включая современные нефтебазы и подземные хранилища.",
      imgSrc: "/bunker.png",
      price: "1 500 000",
      to: "/catalog/7",
      url: "https://ltdfoto.ru/image/slWEPM",
    },
    {
      id: 8,
      title: "Бункеровка",
      description: "«Global Energy Solution» занимает лидирующие позиции на бункерном рынке России, обеспечивая высококачественную бункеровку судов.",
      imgSrc: "/ships.png",
      price: "1 000 000",
      to: "/catalog/8",
      url: "https://ltdfoto.ru/image/slWeXf",
    },
    {
      id: 9,
      title: "Битумы",
      description: "«Global Energy Solution» является одним из крупнейших производителей и поставщиков битумной продукции в России.",
      imgSrc: "/products.png",
      price: "800 000",
      to: "/catalog/9",
      url: "https://ltdfoto.ru/image/slWwpn",
    },
    {
      id: 10,
      title: "Анализ проектов",
      description: "«Global Energy Solution» проводит комплексный анализ проектов, от геологических исследований до финансово-налоговых аспектов.",
      imgSrc: "/money.png",
      price: "500 000",
      to: "/catalog/10",
      url: "https://ltdfoto.ru/image/slWIWY",
    },
    {
      id: 11,
      title: "Автономные системы",
      description: "«Global Energy Solution» разрабатывает и внедряет автономные системы энергообеспечения для промышленных объектов.",
      imgSrc: "/box.png",
      price: "1 200 000",
      to: "/catalog/11",
      url: "https://ltdfoto.ru/image/slWSkh",
    },
    {
      id: 12,
      title: "Транспортировка",
      description: "«Global Energy Solution» обеспечивает надежную транспортировку нефти и газа по трубопроводам, используя современные технологии.",
      imgSrc: "/truba.png",
      price: "2 000 000", 
      to: "/catalog/12",
      url: "https://ltdfoto.ru/image/slWKI3",
    },
  ];